services:
  # --- 1. 添加数据库服务 ---
  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"
  #2---order 数据库----
  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5433:5432" # 注意：宿主机端口改到 5433，避免和 product 的 5432 冲突

  discovery-server:
    image: discovery-server:v1
    container_name: discovery-server
    ports:
      - "8761:8761"

  config-server:
    image: config-server:v1
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      #这一行是关键：[宿主机路径]:[容器内路径]
      - ./config-server/src/main/resources/shared-configs:/config
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
       #告诉 Spring 去容器内的 /config 文件夹找文件
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config/
    depends_on:
      - discovery-server

  product-service:
    image: product-service:v1
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      # 1. 统一使用下划线格式（更稳定）
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product:5432/product_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123
      # 2. 强制指定方言，跳过元数据检测
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      # 3. 告诉它配置中心在哪
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - config-server
      - postgres-product

  order-service:
    image: order-service:v1
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - config-server
      - postgres-order